//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDpage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://podev1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_DEV&receiverParty=&receiverService=&interface=SI_ZPP_MATERIAL_REQ&interfaceNa" +
            "mespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_material_req")]
        public string DDpage_KmrAppMatChWebReference_SI_ZPP_MATERIAL_REQService {
            get {
                return ((string)(this["DDpage_KmrAppMatChWebReference_SI_ZPP_MATERIAL_REQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_RESB_Sender&interfaceNam" +
            "espace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_resb")]
        public string DDpage_Get_KmrStorage_PlanList_SI_ZPP_RESB_SenderService {
            get {
                return ((string)(this["DDpage_Get_KmrStorage_PlanList_SI_ZPP_RESB_SenderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.234:8090/Storage/KmrSendMatService.asmx")]
        public string DDpage_SendToLineLib_KmrSendMatService {
            get {
                return ((string)(this["DDpage_SendToLineLib_KmrSendMatService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_GOODSMVT&interfaceNamesp" +
            "ace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_goodsmvt")]
        public string DDpage_KmrAppComPick_SI_ZPP_GOODSMVTService {
            get {
                return ((string)(this["DDpage_KmrAppComPick_SI_ZPP_GOODSMVTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_RESERVATION_CREATE_Sende" +
            "r&interfaceNamespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_reservation_create")]
        public string DDpage_KmrAppMatCreateRsNo_SI_ZPP_RESERVATION_CREATE_SenderService {
            get {
                return ((string)(this["DDpage_KmrAppMatCreateRsNo_SI_ZPP_RESERVATION_CREATE_SenderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_MATERIAL_REQ&interfaceNa" +
            "mespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_material_req")]
        public string DDpage_KmrAppMatPick_SI_ZPP_MATERIAL_REQService {
            get {
                return ((string)(this["DDpage_KmrAppMatPick_SI_ZPP_MATERIAL_REQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZDM_EKES&interfaceNamespace=" +
            "http%3A%2F%2Fwww.kocel.com%2Flims%2Fzdm_ekes")]
        public string DDpage_Get_KmrApp_PurOrder_SI_ZDM_EKESService {
            get {
                return ((string)(this["DDpage_Get_KmrApp_PurOrder_SI_ZDM_EKESService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_GOODSINVOCHER&interfaceN" +
            "amespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_goodsinvocher")]
        public string DDpage_Post_KmrApp_CheckIn_SI_ZPP_GOODSINVOCHERService {
            get {
                return ((string)(this["DDpage_Post_KmrApp_CheckIn_SI_ZPP_GOODSINVOCHERService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_GOODSMVT_201&interfaceNa" +
            "mespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_goodsmvt_201")]
        public string DDpage_Post_KmrApp_OutComCostPick_SI_ZPP_GOODSMVT_201Service {
            get {
                return ((string)(this["DDpage_Post_KmrApp_OutComCostPick_SI_ZPP_GOODSMVT_201Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZDM_INVENTORY_Sender&interfa" +
            "ceNamespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzdm_inventoryinf")]
        public string DDpage_Get_KmrApp_Inventory_SI_ZDM_INVENTORY_SenderService {
            get {
                return ((string)(this["DDpage_Get_KmrApp_Inventory_SI_ZDM_INVENTORY_SenderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poprd1:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_LI" +
            "MS_PRD&receiverParty=&receiverService=&interface=SI_ZPP_GOODSMVT_Z04&interfaceNa" +
            "mespace=http%3A%2F%2Fwww.kocel.com%2Flims%2Fzpp_goodsmvt_z04")]
        public string DDpage_Post_KmrApp_ComResearchPick_SI_ZPP_GOODSMVT_Z04Service {
            get {
                return ((string)(this["DDpage_Post_KmrApp_ComResearchPick_SI_ZPP_GOODSMVT_Z04Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzxproductresb/800/zzxproductresb/zz" +
            "xproductresb")]
        public string DDpage_ProductOrderYuLiu_ZZXPRODUCTRESB {
            get {
                return ((string)(this["DDpage_ProductOrderYuLiu_ZZXPRODUCTRESB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ERPPRD.YANTAIMOON.COM:8001/sap/bc/srt/rfc/sap/zxrealtimestore/800/zxrealti" +
            "mestore/zxrealtimestore")]
        public string DDpage_InTimeStock_ZXREALTIMESTORE {
            get {
                return ((string)(this["DDpage_InTimeStock_ZXREALTIMESTORE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzxplan/800/zzxplan/zzxplan")]
        public string DDpage_PlanIn_ZZXPLAN {
            get {
                return ((string)(this["DDpage_PlanIn_ZZXPLAN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzxnoplan/800/zzxnoplan/zzxnoplan")]
        public string DDpage_PlanOut_ZZXNOPLAN {
            get {
                return ((string)(this["DDpage_PlanOut_ZZXNOPLAN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzxkostl201/800/zzxkostl201/zzxkostl" +
            "201")]
        public string DDpage_CoastCenter_ZZXKOSTL201 {
            get {
                return ((string)(this["DDpage_CoastCenter_ZZXKOSTL201"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzxmoveorder/800/zzxmoveorder/zzxmov" +
            "eorder")]
        public string DDpage_InnerOrder_ZZXMOVEORDER {
            get {
                return ((string)(this["DDpage_InnerOrder_ZZXMOVEORDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zpomigo/800/zpomigo/zpomigo")]
        public string DDpage_PoRuku_ZPOMIGO {
            get {
                return ((string)(this["DDpage_PoRuku_ZPOMIGO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzx_getpo/800/zzx_getpo/zzx_getpo")]
        public string DDpage_PO_ZZX_GETPO {
            get {
                return ((string)(this["DDpage_PO_ZZX_GETPO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zmove311/800/zmove311/zmove311")]
        public string DDpage_YiKu311_ZMOVE311 {
            get {
                return ((string)(this["DDpage_YiKu311_ZMOVE311"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.42:8001/sap/bc/srt/rfc/sap/zzx_getorderconfirm/800/zzx_getorder" +
            "confirm/zzx_getorderconfirm")]
        public string DDpage_GetSapProductOrder_ZZX_GETORDERCONFIRM {
            get {
                return ((string)(this["DDpage_GetSapProductOrder_ZZX_GETORDERCONFIRM"]));
            }
        }
    }
}
