//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDpage.PoRuku {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZPOMIGO", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPOMIGO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZPP_PO_MOVEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZPOMIGO() {
            this.Url = global::DDpage.Properties.Settings.Default.DDpage_PoRuku_ZPOMIGO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZPP_PO_MOVECompletedEventHandler ZPP_PO_MOVECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZPOMIGO:ZPP_PO_MOVERequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZPP_PO_MOVEResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZPP_PO_MOVEResponse ZPP_PO_MOVE([System.Xml.Serialization.XmlElementAttribute("ZPP_PO_MOVE", Namespace="urn:sap-com:document:sap:rfc:functions")] ZPP_PO_MOVE ZPP_PO_MOVE1) {
            object[] results = this.Invoke("ZPP_PO_MOVE", new object[] {
                        ZPP_PO_MOVE1});
            return ((ZPP_PO_MOVEResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZPP_PO_MOVEAsync(ZPP_PO_MOVE ZPP_PO_MOVE1) {
            this.ZPP_PO_MOVEAsync(ZPP_PO_MOVE1, null);
        }
        
        /// <remarks/>
        public void ZPP_PO_MOVEAsync(ZPP_PO_MOVE ZPP_PO_MOVE1, object userState) {
            if ((this.ZPP_PO_MOVEOperationCompleted == null)) {
                this.ZPP_PO_MOVEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZPP_PO_MOVEOperationCompleted);
            }
            this.InvokeAsync("ZPP_PO_MOVE", new object[] {
                        ZPP_PO_MOVE1}, this.ZPP_PO_MOVEOperationCompleted, userState);
        }
        
        private void OnZPP_PO_MOVEOperationCompleted(object arg) {
            if ((this.ZPP_PO_MOVECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZPP_PO_MOVECompleted(this, new ZPP_PO_MOVECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_PO_MOVE {
        
        private string zBWARTField;
        
        private string zEBELNField;
        
        private string zEBELPField;
        
        private decimal zWEMNGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBWART {
            get {
                return this.zBWARTField;
            }
            set {
                this.zBWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEBELN {
            get {
                return this.zEBELNField;
            }
            set {
                this.zEBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEBELP {
            get {
                return this.zEBELPField;
            }
            set {
                this.zEBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ZWEMNG {
            get {
                return this.zWEMNGField;
            }
            set {
                this.zWEMNGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_PO_MOVEResponse {
        
        private string e_MSGTXField;
        
        private string e_MSGTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_MSGTX {
            get {
                return this.e_MSGTXField;
            }
            set {
                this.e_MSGTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_MSGTY {
            get {
                return this.e_MSGTYField;
            }
            set {
                this.e_MSGTYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZPP_PO_MOVECompletedEventHandler(object sender, ZPP_PO_MOVECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZPP_PO_MOVECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZPP_PO_MOVECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZPP_PO_MOVEResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPP_PO_MOVEResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591