//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDpage.InnerOrder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZZXMOVEORDER", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZXMOVEORDER : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZMM_MOVE_IORDEROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZZXMOVEORDER() {
            this.Url = global::DDpage.Properties.Settings.Default.DDpage_InnerOrder_ZZXMOVEORDER;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZMM_MOVE_IORDERCompletedEventHandler ZMM_MOVE_IORDERCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZZXMOVEORDER:ZMM_MOVE_IORDERRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMM_MOVE_IORDERResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMM_MOVE_IORDERResponse ZMM_MOVE_IORDER([System.Xml.Serialization.XmlElementAttribute("ZMM_MOVE_IORDER", Namespace="urn:sap-com:document:sap:rfc:functions")] ZMM_MOVE_IORDER ZMM_MOVE_IORDER1) {
            object[] results = this.Invoke("ZMM_MOVE_IORDER", new object[] {
                        ZMM_MOVE_IORDER1});
            return ((ZMM_MOVE_IORDERResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZMM_MOVE_IORDERAsync(ZMM_MOVE_IORDER ZMM_MOVE_IORDER1) {
            this.ZMM_MOVE_IORDERAsync(ZMM_MOVE_IORDER1, null);
        }
        
        /// <remarks/>
        public void ZMM_MOVE_IORDERAsync(ZMM_MOVE_IORDER ZMM_MOVE_IORDER1, object userState) {
            if ((this.ZMM_MOVE_IORDEROperationCompleted == null)) {
                this.ZMM_MOVE_IORDEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnZMM_MOVE_IORDEROperationCompleted);
            }
            this.InvokeAsync("ZMM_MOVE_IORDER", new object[] {
                        ZMM_MOVE_IORDER1}, this.ZMM_MOVE_IORDEROperationCompleted, userState);
        }
        
        private void OnZMM_MOVE_IORDEROperationCompleted(object arg) {
            if ((this.ZMM_MOVE_IORDERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZMM_MOVE_IORDERCompleted(this, new ZMM_MOVE_IORDERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_MOVE_IORDER {
        
        private string zAUFNRField;
        
        private string zBWARTField;
        
        private ZZXGOODSMOVE[] zGOODSMOVEField;
        
        private string zLGORTField;
        
        private string zWERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZAUFNR {
            get {
                return this.zAUFNRField;
            }
            set {
                this.zAUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBWART {
            get {
                return this.zBWARTField;
            }
            set {
                this.zBWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZXGOODSMOVE[] ZGOODSMOVE {
            get {
                return this.zGOODSMOVEField;
            }
            set {
                this.zGOODSMOVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZLGORT {
            get {
                return this.zLGORTField;
            }
            set {
                this.zLGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZWERKS {
            get {
                return this.zWERKSField;
            }
            set {
                this.zWERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZZXGOODSMOVE {
        
        private string mATNRField;
        
        private decimal eRFMGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERFMG {
            get {
                return this.eRFMGField;
            }
            set {
                this.eRFMGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_MOVE_IORDERResponse {
        
        private string e_MSGTXField;
        
        private string e_MSGTYField;
        
        private ZZXGOODSMOVE[] zGOODSMOVEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_MSGTX {
            get {
                return this.e_MSGTXField;
            }
            set {
                this.e_MSGTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_MSGTY {
            get {
                return this.e_MSGTYField;
            }
            set {
                this.e_MSGTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZZXGOODSMOVE[] ZGOODSMOVE {
            get {
                return this.zGOODSMOVEField;
            }
            set {
                this.zGOODSMOVEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZMM_MOVE_IORDERCompletedEventHandler(object sender, ZMM_MOVE_IORDERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZMM_MOVE_IORDERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZMM_MOVE_IORDERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZMM_MOVE_IORDERResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZMM_MOVE_IORDERResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591