//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDpage.KmrAppComPick {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ZPP_GOODSMVTBinding", Namespace="http://www.kocel.com/lims/zpp_goodsmvt")]
    public partial class SI_ZPP_GOODSMVTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ZPP_GOODSMVTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ZPP_GOODSMVTService() {
            this.Url = global::DDpage.Properties.Settings.Default.DDpage_KmrAppComPick_SI_ZPP_GOODSMVTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ZPP_GOODSMVTCompletedEventHandler SI_ZPP_GOODSMVTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZPP_GOODSMVTResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZPP_GOODSMVTResponse SI_ZPP_GOODSMVT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZPP_GOODSMVT ZPP_GOODSMVT) {
            object[] results = this.Invoke("SI_ZPP_GOODSMVT", new object[] {
                        ZPP_GOODSMVT});
            return ((ZPP_GOODSMVTResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SI_ZPP_GOODSMVTAsync(ZPP_GOODSMVT ZPP_GOODSMVT) {
            this.SI_ZPP_GOODSMVTAsync(ZPP_GOODSMVT, null);
        }
        
        /// <remarks/>
        public void SI_ZPP_GOODSMVTAsync(ZPP_GOODSMVT ZPP_GOODSMVT, object userState) {
            if ((this.SI_ZPP_GOODSMVTOperationCompleted == null)) {
                this.SI_ZPP_GOODSMVTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ZPP_GOODSMVTOperationCompleted);
            }
            this.InvokeAsync("SI_ZPP_GOODSMVT", new object[] {
                        ZPP_GOODSMVT}, this.SI_ZPP_GOODSMVTOperationCompleted, userState);
        }
        
        private void OnSI_ZPP_GOODSMVTOperationCompleted(object arg) {
            if ((this.SI_ZPP_GOODSMVTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ZPP_GOODSMVTCompleted(this, new SI_ZPP_GOODSMVTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_GOODSMVT {
        
        private ZSD_GOODSMVTHEADER[] zSD_GOODSMVTHEADERField;
        
        private ZSD_GOODSMVTITEM[] zSD_GOODSMVTITEMField;
        
        private ZSD_GOODSMVTRETURN[] zSD_GOODSMVTRETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTHEADER[] ZSD_GOODSMVTHEADER {
            get {
                return this.zSD_GOODSMVTHEADERField;
            }
            set {
                this.zSD_GOODSMVTHEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTITEM[] ZSD_GOODSMVTITEM {
            get {
                return this.zSD_GOODSMVTITEMField;
            }
            set {
                this.zSD_GOODSMVTITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTRETURN[] ZSD_GOODSMVTRETURN {
            get {
                return this.zSD_GOODSMVTRETURNField;
            }
            set {
                this.zSD_GOODSMVTRETURNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_GOODSMVTHEADER {
        
        private string bUDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_GOODSMVTRETURN {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_GOODSMVTITEM {
        
        private string sTGE_LOCField;
        
        private string bATCHField;
        
        private string kZBEWField;
        
        private string rESERVATION_NUMBERField;
        
        private decimal eRFMGField;
        
        private string pLANTField;
        
        private string mATERIALField;
        
        private string cOSTCENTERField;
        
        private string eNTRY_UOMField;
        
        private string mOVE_TYPEField;
        
        private string rES_ITEMField;
        
        private string oRDERIDField;
        
        private string pARGBField;
        
        private string vORNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STGE_LOC {
            get {
                return this.sTGE_LOCField;
            }
            set {
                this.sTGE_LOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BATCH {
            get {
                return this.bATCHField;
            }
            set {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KZBEW {
            get {
                return this.kZBEWField;
            }
            set {
                this.kZBEWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVATION_NUMBER {
            get {
                return this.rESERVATION_NUMBERField;
            }
            set {
                this.rESERVATION_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERFMG {
            get {
                return this.eRFMGField;
            }
            set {
                this.eRFMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COSTCENTER {
            get {
                return this.cOSTCENTERField;
            }
            set {
                this.cOSTCENTERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRY_UOM {
            get {
                return this.eNTRY_UOMField;
            }
            set {
                this.eNTRY_UOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOVE_TYPE {
            get {
                return this.mOVE_TYPEField;
            }
            set {
                this.mOVE_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RES_ITEM {
            get {
                return this.rES_ITEMField;
            }
            set {
                this.rES_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDERID {
            get {
                return this.oRDERIDField;
            }
            set {
                this.oRDERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARGB {
            get {
                return this.pARGBField;
            }
            set {
                this.pARGBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VORNR {
            get {
                return this.vORNRField;
            }
            set {
                this.vORNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_GOODSMVTResponse {
        
        private string iNFOField;
        
        private string mBLNRField;
        
        private string mESSGField;
        
        private string mJAHRField;
        
        private ZSD_GOODSMVTHEADER[] zSD_GOODSMVTHEADERField;
        
        private ZSD_GOODSMVTITEM[] zSD_GOODSMVTITEMField;
        
        private ZSD_GOODSMVTRETURN[] zSD_GOODSMVTRETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSG {
            get {
                return this.mESSGField;
            }
            set {
                this.mESSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MJAHR {
            get {
                return this.mJAHRField;
            }
            set {
                this.mJAHRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTHEADER[] ZSD_GOODSMVTHEADER {
            get {
                return this.zSD_GOODSMVTHEADERField;
            }
            set {
                this.zSD_GOODSMVTHEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTITEM[] ZSD_GOODSMVTITEM {
            get {
                return this.zSD_GOODSMVTITEMField;
            }
            set {
                this.zSD_GOODSMVTITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVTRETURN[] ZSD_GOODSMVTRETURN {
            get {
                return this.zSD_GOODSMVTRETURNField;
            }
            set {
                this.zSD_GOODSMVTRETURNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SI_ZPP_GOODSMVTCompletedEventHandler(object sender, SI_ZPP_GOODSMVTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_ZPP_GOODSMVTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_ZPP_GOODSMVTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZPP_GOODSMVTResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPP_GOODSMVTResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591