//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36373
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.36373 版自动生成。
// 
#pragma warning disable 1591

namespace DDpage.Post_KmrApp_ComResearchPick {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ZPP_GOODSMVT_Z04Binding", Namespace="http://www.kocel.com/lims/zpp_goodsmvt_z04")]
    public partial class SI_ZPP_GOODSMVT_Z04Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ZPP_GOODSMVT_Z04OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ZPP_GOODSMVT_Z04Service() {
            this.Url = global::DDpage.Properties.Settings.Default.DDpage_Post_KmrApp_ComResearchPick_SI_ZPP_GOODSMVT_Z04Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ZPP_GOODSMVT_Z04CompletedEventHandler SI_ZPP_GOODSMVT_Z04Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZPP_GOODSMVT_Z04Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZPP_GOODSMVT_Z04Response SI_ZPP_GOODSMVT_Z04([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZPP_GOODSMVT_Z04 ZPP_GOODSMVT_Z04) {
            object[] results = this.Invoke("SI_ZPP_GOODSMVT_Z04", new object[] {
                        ZPP_GOODSMVT_Z04});
            return ((ZPP_GOODSMVT_Z04Response)(results[0]));
        }
        
        /// <remarks/>
        public void SI_ZPP_GOODSMVT_Z04Async(ZPP_GOODSMVT_Z04 ZPP_GOODSMVT_Z04) {
            this.SI_ZPP_GOODSMVT_Z04Async(ZPP_GOODSMVT_Z04, null);
        }
        
        /// <remarks/>
        public void SI_ZPP_GOODSMVT_Z04Async(ZPP_GOODSMVT_Z04 ZPP_GOODSMVT_Z04, object userState) {
            if ((this.SI_ZPP_GOODSMVT_Z04OperationCompleted == null)) {
                this.SI_ZPP_GOODSMVT_Z04OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ZPP_GOODSMVT_Z04OperationCompleted);
            }
            this.InvokeAsync("SI_ZPP_GOODSMVT_Z04", new object[] {
                        ZPP_GOODSMVT_Z04}, this.SI_ZPP_GOODSMVT_Z04OperationCompleted, userState);
        }
        
        private void OnSI_ZPP_GOODSMVT_Z04OperationCompleted(object arg) {
            if ((this.SI_ZPP_GOODSMVT_Z04Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ZPP_GOODSMVT_Z04Completed(this, new SI_ZPP_GOODSMVT_Z04CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_GOODSMVT_Z04 {
        
        private ZSD_GOODSMVT_HEAD[] zSD_GOODSMVT_HEADField;
        
        private ZSD_GOODSMVT_ITEM[] zSD_GOODSMVT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVT_HEAD[] ZSD_GOODSMVT_HEAD {
            get {
                return this.zSD_GOODSMVT_HEADField;
            }
            set {
                this.zSD_GOODSMVT_HEADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVT_ITEM[] ZSD_GOODSMVT_ITEM {
            get {
                return this.zSD_GOODSMVT_ITEMField;
            }
            set {
                this.zSD_GOODSMVT_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_GOODSMVT_HEAD {
        
        private string bWARTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_GOODSMVT_ITEM {
        
        private string rSNUMField;
        
        private string rSPOSField;
        
        private string aUFNRField;
        
        private string vORNRField;
        
        private string lGORTField;
        
        private string cHARGField;
        
        private decimal bDMNGField;
        
        private string wERKSField;
        
        private string mATNRField;
        
        private string pARGBField;
        
        private string sOBKZField;
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string mOV_WERKSField;
        
        private string mOV_LGORTField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSNUM {
            get {
                return this.rSNUMField;
            }
            set {
                this.rSNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSPOS {
            get {
                return this.rSPOSField;
            }
            set {
                this.rSPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VORNR {
            get {
                return this.vORNRField;
            }
            set {
                this.vORNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHARG {
            get {
                return this.cHARGField;
            }
            set {
                this.cHARGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BDMNG {
            get {
                return this.bDMNGField;
            }
            set {
                this.bDMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARGB {
            get {
                return this.pARGBField;
            }
            set {
                this.pARGBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOBKZ {
            get {
                return this.sOBKZField;
            }
            set {
                this.sOBKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOV_WERKS {
            get {
                return this.mOV_WERKSField;
            }
            set {
                this.mOV_WERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOV_LGORT {
            get {
                return this.mOV_LGORTField;
            }
            set {
                this.mOV_LGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPP_GOODSMVT_Z04Response {
        
        private ZSD_GOODSMVT_HEAD[] zSD_GOODSMVT_HEADField;
        
        private ZSD_GOODSMVT_ITEM[] zSD_GOODSMVT_ITEMField;
        
        private string z_MSGTXField;
        
        private string z_MSGTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVT_HEAD[] ZSD_GOODSMVT_HEAD {
            get {
                return this.zSD_GOODSMVT_HEADField;
            }
            set {
                this.zSD_GOODSMVT_HEADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_GOODSMVT_ITEM[] ZSD_GOODSMVT_ITEM {
            get {
                return this.zSD_GOODSMVT_ITEMField;
            }
            set {
                this.zSD_GOODSMVT_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_MSGTX {
            get {
                return this.z_MSGTXField;
            }
            set {
                this.z_MSGTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_MSGTY {
            get {
                return this.z_MSGTYField;
            }
            set {
                this.z_MSGTYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void SI_ZPP_GOODSMVT_Z04CompletedEventHandler(object sender, SI_ZPP_GOODSMVT_Z04CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_ZPP_GOODSMVT_Z04CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_ZPP_GOODSMVT_Z04CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZPP_GOODSMVT_Z04Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZPP_GOODSMVT_Z04Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591