//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDpage.KmrAppMatSendToLineLib {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KmrSendMatServiceSoap", Namespace="http://tempuri.org/")]
    public partial class KmrSendMatService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendToLineLibOperationCompleted;
        
        private System.Threading.SendOrPostCallback creratePickMatPlanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KmrSendMatService() {
            this.Url = global::DDpage.Properties.Settings.Default.DDpage_SendToLineLib_KmrSendMatService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendToLineLibCompletedEventHandler SendToLineLibCompleted;
        
        /// <remarks/>
        public event creratePickMatPlanCompletedEventHandler creratePickMatPlanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendToLineLib", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendToLineLib(string strJson) {
            object[] results = this.Invoke("SendToLineLib", new object[] {
                        strJson});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendToLineLibAsync(string strJson) {
            this.SendToLineLibAsync(strJson, null);
        }
        
        /// <remarks/>
        public void SendToLineLibAsync(string strJson, object userState) {
            if ((this.SendToLineLibOperationCompleted == null)) {
                this.SendToLineLibOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendToLineLibOperationCompleted);
            }
            this.InvokeAsync("SendToLineLib", new object[] {
                        strJson}, this.SendToLineLibOperationCompleted, userState);
        }
        
        private void OnSendToLineLibOperationCompleted(object arg) {
            if ((this.SendToLineLibCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendToLineLibCompleted(this, new SendToLineLibCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creratePickMatPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string creratePickMatPlan(string facCode, string perNo, string matCode, string matNum) {
            object[] results = this.Invoke("creratePickMatPlan", new object[] {
                        facCode,
                        perNo,
                        matCode,
                        matNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void creratePickMatPlanAsync(string facCode, string perNo, string matCode, string matNum) {
            this.creratePickMatPlanAsync(facCode, perNo, matCode, matNum, null);
        }
        
        /// <remarks/>
        public void creratePickMatPlanAsync(string facCode, string perNo, string matCode, string matNum, object userState) {
            if ((this.creratePickMatPlanOperationCompleted == null)) {
                this.creratePickMatPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreratePickMatPlanOperationCompleted);
            }
            this.InvokeAsync("creratePickMatPlan", new object[] {
                        facCode,
                        perNo,
                        matCode,
                        matNum}, this.creratePickMatPlanOperationCompleted, userState);
        }
        
        private void OncreratePickMatPlanOperationCompleted(object arg) {
            if ((this.creratePickMatPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.creratePickMatPlanCompleted(this, new creratePickMatPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendToLineLibCompletedEventHandler(object sender, SendToLineLibCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendToLineLibCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendToLineLibCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void creratePickMatPlanCompletedEventHandler(object sender, creratePickMatPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class creratePickMatPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal creratePickMatPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591